name: gym_env
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - ld_impl_linux-64=2.45
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - python=3.8.20
  - readline=8.3
  - tk=8.6.13
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zstd=1.5.7
  - pip:
      - cloudpickle==1.6.0
      - future==1.0.0
      - gym==0.19.0
      - importlib-metadata==8.5.0
      - llvmlite==0.41.1
      - numba==0.58.1
      - numpy==1.22.0
      - pillow==10.4.0
      - pip==21.0
      - pyglet==1.4.11
      - pyopengl==3.1.10
      - pyyaml==6.0.3
      - scipy==1.10.1
      - setuptools==65.5.0
      - wheel==0.38.0
      - zipp==3.20.2
prefix: /home/pganguli/.config/conda/envs/gym_env
